<?php
require_once __DIR__ . '/config.php'; require_admin();
$pageTitle = 'Admin Dashboard — MediTrade'; $errors = [];
$tab = (string)($_GET['tab'] ?? 'overview'); if (!in_array($tab, ['overview','products','orders'], true)) $tab = 'overview';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $action = (string)($_POST['action'] ?? '');
    try {
        if ($action === 'save_product') {
            $id = (int)($_POST['id'] ?? 0); $name = trim((string)($_POST['name'] ?? '')); $brand = trim((string)($_POST['brand'] ?? '')); $category = trim((string)($_POST['category'] ?? '')); $code = trim((string)($_POST['product_code'] ?? '')); $pack = trim((string)($_POST['pack_size'] ?? '')); $description = trim((string)($_POST['description'] ?? '')); $price = filter_var($_POST['price'] ?? null, FILTER_VALIDATE_FLOAT); $stock = filter_var($_POST['stock'] ?? null, FILTER_VALIDATE_INT);
            if ($name === '' || $brand === '' || $category === '' || $code === '' || $pack === '' || $price === false || $price <= 0 || $stock === false || $stock < 0) throw new RuntimeException('Complete all required product fields with valid price and stock.');
            if ($id) { $st = $pdo->prepare('UPDATE products SET name=?,brand=?,category=?,product_code=?,pack_size=?,description=?,price=?,stock=? WHERE id=?'); $st->execute([$name,$brand,$category,$code,$pack,$description,$price,$stock,$id]); set_flash('Product updated.'); }
            else { $st = $pdo->prepare('INSERT INTO products (name,brand,category,product_code,pack_size,description,price,stock,is_active) VALUES (?,?,?,?,?,?,?,?,1)'); $st->execute([$name,$brand,$category,$code,$pack,$description,$price,$stock]); set_flash('Product added.'); }
            header('Location: admin.php?tab=products'); exit;
        }
        if ($action === 'toggle_product') { $id=(int)($_POST['id'] ?? 0); $st=$pdo->prepare('UPDATE products SET is_active = IF(is_active=1,0,1) WHERE id=?'); $st->execute([$id]); set_flash('Product visibility updated.'); header('Location: admin.php?tab=products'); exit; }
        if ($action === 'update_order') { $id=(int)($_POST['id'] ?? 0); $status=(string)($_POST['status'] ?? 'Pending'); $allowed=['Pending','Processing','Shipped','Completed','Cancelled']; if (!in_array($status,$allowed,true)) throw new RuntimeException('Invalid order status.'); $st=$pdo->prepare('UPDATE orders SET status=? WHERE id=?'); $st->execute([$status,$id]); set_flash('Order status updated.'); header('Location: admin.php?tab=orders'); exit; }
    } catch (Throwable $ex) { $errors[] = $ex instanceof RuntimeException ? $ex->getMessage() : 'Could not save changes. Check for duplicate product codes and try again.'; }
}
$counts = [
 'products'=>(int)$pdo->query('SELECT COUNT(*) FROM products WHERE is_active=1')->fetchColumn(),
 'buyers'=>(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='buyer'")->fetchColumn(),
 'orders'=>(int)$pdo->query("SELECT COUNT(*) FROM orders")->fetchColumn(),
 'pending'=>(int)$pdo->query("SELECT COUNT(*) FROM orders WHERE status='Pending'")->fetchColumn(),
 'sales'=>(float)$pdo->query("SELECT COALESCE(SUM(total_amount),0) FROM orders WHERE status IN ('Processing','Shipped','Completed')")->fetchColumn()
];
$products = $pdo->query('SELECT * FROM products ORDER BY created_at DESC')->fetchAll();
$orders = $pdo->query('SELECT o.id,o.total_amount,o.status,o.created_at,u.name,u.business_name FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC LIMIT 100')->fetchAll();
$editProduct = null; if (isset($_GET['edit'])) { $st=$pdo->prepare('SELECT * FROM products WHERE id=?'); $st->execute([(int)$_GET['edit']]); $editProduct=$st->fetch(); }
require __DIR__ . '/partials/header.php';
?>
<section class="page-hero admin-hero"><div class="container admin-heading"><div><span class="eyebrow">MEDITRADE CONTROL CENTRE</span><h1>Admin dashboard</h1><p>Manage catalogue, inventory and buyer orders from one place.</p></div><span class="admin-avatar">✚</span></div></section>
<section class="section container">
<?php if ($errors): ?><div class="form-errors"><?php foreach($errors as $err): ?><p><?= e($err) ?></p><?php endforeach; ?></div><?php endif; ?>
<div class="admin-tabs"><a class="<?= $tab==='overview'?'active':'' ?>" href="admin.php">Overview</a><a class="<?= $tab==='products'?'active':'' ?>" href="admin.php?tab=products">Products</a><a class="<?= $tab==='orders'?'active':'' ?>" href="admin.php?tab=orders">Orders</a></div>
<?php if ($tab === 'overview'): ?>
<div class="stats-grid"><div class="stat-card"><span>Active products</span><strong><?= $counts['products'] ?></strong><small>In catalogue</small></div><div class="stat-card"><span>Registered buyers</span><strong><?= $counts['buyers'] ?></strong><small>Buyer accounts</small></div><div class="stat-card"><span>Total orders</span><strong><?= $counts['orders'] ?></strong><small>All statuses</small></div><div class="stat-card"><span>Pending orders</span><strong><?= $counts['pending'] ?></strong><small>Awaiting review</small></div></div>
<div class="admin-content-grid"><div class="table-card"><div class="table-card-heading"><div><h2>Recent orders</h2><p>Latest buyer activity</p></div><a class="text-link" href="admin.php?tab=orders">View all →</a></div><div class="table-scroll"><table><thead><tr><th>Order</th><th>Buyer</th><th>Total</th><th>Status</th></tr></thead><tbody><?php foreach (array_slice($orders,0,6) as $o): ?><tr><td><a class="text-link" href="order.php?id=<?= (int)$o['id'] ?>">#MT-<?= (int)$o['id'] ?></a></td><td><?= e($o['business_name'] ?: $o['name']) ?></td><td><?= money($o['total_amount']) ?></td><td><span class="status status-<?= strtolower(e($o['status'])) ?>"><?= e($o['status']) ?></span></td></tr><?php endforeach; ?><?php if (!$orders): ?><tr><td colspan="4">No orders yet.</td></tr><?php endif; ?></tbody></table></div></div><div class="quick-actions"><h2>Quick actions</h2><p>Keep your catalogue current.</p><a class="quick-action" href="admin.php?tab=products"><span>＋</span><div><strong>Add a product</strong><small>Create a catalogue listing</small></div><b>→</b></a><a class="quick-action" href="admin.php?tab=orders"><span>▤</span><div><strong>Process orders</strong><small>Review buyer requests</small></div><b>→</b></a><a class="quick-action" href="catalog.php"><span>⌕</span><div><strong>View storefront</strong><small>Check the buyer experience</small></div><b>→</b></a></div></div>
<?php elseif ($tab === 'products'): ?>
<div class="admin-section-heading"><div><h2>Product catalogue</h2><p>Add products or update stock and prices.</p></div><a class="btn btn-primary" href="admin.php?tab=products#product-form">＋ Add product</a></div>
<?php if (isset($_GET['edit']) && !$editProduct): ?><div class="form-errors"><p>Product not found.</p></div><?php endif; ?>
<div class="admin-product-layout"><div class="table-card"><div class="table-scroll"><table><thead><tr><th>Product</th><th>Price</th><th>Stock</th><th>Visibility</th><th>Actions</th></tr></thead><tbody><?php foreach($products as $p): ?><tr><td><strong><?= e($p['name']) ?></strong><small class="table-sub"><?= e($p['brand']) ?> · <?= e($p['category']) ?></small></td><td><?= money($p['price']) ?></td><td><span class="<?= $p['stock'] < 10 ? 'stock-low' : 'stock-good' ?>"><?= (int)$p['stock'] ?></span></td><td><?= $p['is_active'] ? 'Active' : 'Hidden' ?></td><td><div class="table-actions"><a class="text-link" href="admin.php?tab=products&edit=<?= (int)$p['id'] ?>#product-form">Edit</a><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$p['id'] ?>"><button class="text-button" name="action" value="toggle_product"><?= $p['is_active'] ? 'Hide' : 'Activate' ?></button></form></div></td></tr><?php endforeach; ?></tbody></table></div></div>
<div class="auth-card product-editor" id="product-form"><span class="eyebrow"><?= $editProduct ? 'EDIT LISTING' : 'NEW LISTING' ?></span><h2><?= $editProduct ? 'Update product' : 'Add a product' ?></h2><form method="post" class="form-stack"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)($editProduct['id'] ?? 0) ?>"><input type="hidden" name="action" value="save_product"><label>Product name<input name="name" required maxlength="160" value="<?= e($editProduct['name'] ?? '') ?>"></label><label>Brand<input name="brand" required maxlength="120" value="<?= e($editProduct['brand'] ?? '') ?>"></label><label>Category<input name="category" required maxlength="80" placeholder="e.g. Wellness" value="<?= e($editProduct['category'] ?? '') ?>"></label><label>Product code / SKU<input name="product_code" required maxlength="60" value="<?= e($editProduct['product_code'] ?? '') ?>"></label><label>Pack size<input name="pack_size" required maxlength="80" placeholder="e.g. Pack of 10" value="<?= e($editProduct['pack_size'] ?? '') ?>"></label><label>Description<textarea name="description" rows="3" maxlength="1000"><?= e($editProduct['description'] ?? '') ?></textarea></label><div class="form-two"><label>Price (₹)<input type="number" name="price" min="0.01" step="0.01" required value="<?= e((string)($editProduct['price'] ?? '')) ?>"></label><label>Stock<input type="number" name="stock" min="0" step="1" required value="<?= e((string)($editProduct['stock'] ?? '0')) ?>"></label></div><button class="btn btn-primary btn-block" type="submit"><?= $editProduct ? 'Save changes' : 'Add product' ?></button><?php if($editProduct): ?><a class="btn btn-outline btn-block" href="admin.php?tab=products#product-form">Cancel edit</a><?php endif; ?></form></div></div>
<?php else: ?>
<div class="admin-section-heading"><div><h2>Order management</h2><p>Update order status as the demo workflow progresses.</p></div><span class="status"><?= count($orders) ?> recent orders</span></div>
<div class="table-card"><div class="table-scroll"><table><thead><tr><th>Order</th><th>Buyer</th><th>Date</th><th>Total</th><th>Status</th><th>Update status</th></tr></thead><tbody><?php foreach($orders as $o): ?><tr><td><a class="text-link" href="order.php?id=<?= (int)$o['id'] ?>">#MT-<?= (int)$o['id'] ?></a></td><td><?= e($o['business_name'] ?: $o['name']) ?></td><td><?= e(date('d M Y',strtotime($o['created_at']))) ?></td><td><?= money($o['total_amount']) ?></td><td><span class="status status-<?= strtolower(e($o['status'])) ?>"><?= e($o['status']) ?></span></td><td><form method="post" class="status-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="id" value="<?= (int)$o['id'] ?>"><select name="status" aria-label="Order status"><?php foreach(['Pending','Processing','Shipped','Completed','Cancelled'] as $s): ?><option <?= $o['status']===$s?'selected':'' ?> value="<?= e($s) ?>"><?= e($s) ?></option><?php endforeach; ?></select><button class="btn btn-primary btn-small" name="action" value="update_order">Save</button></form></td></tr><?php endforeach; ?><?php if(!$orders): ?><tr><td colspan="6">No orders have been placed yet.</td></tr><?php endif; ?></tbody></table></div></div>
<?php endif; ?>
</section>
<?php require __DIR__ . '/partials/footer.php'; ?>
